#!/usr/bin/env node
'use strict'
const sdk = require('./index.cjs')
const flags = { source: 'source', protocol: 'protocol', country: 'country', anonymity: 'anonymity', https: 'https', 'max-latency-ms': 'maxLatencyMs', 'min-uptime7d': 'minUptime7d', 'min-checks7d': 'minChecks7d', 'checked-within-min': 'checkedWithinMin', limit: 'limit', format: 'format' }
const parse = args => { const out = {}; for (let i = 0; i < args.length; i += 1) { const key = args[i].replace(/^--/, ''); if (!flags[key]) throw new Error(`Unknown option --${key}`); const value = args[++i]; if (value === undefined) throw new Error(`Missing value for --${key}`); out[flags[key]] = ['https'].includes(key) ? value === 'true' : ['limit', 'max-latency-ms', 'min-uptime7d', 'min-checks7d', 'checked-within-min'].includes(key) ? Number(value) : value } return out }
const csv = rows => { const keys = Object.keys(rows[0] || {}); const cell = x => x == null ? '' : /[",\n]/.test(String(x)) ? `"${String(x).replace(/"/g, '""')}"` : String(x); return [keys.join(','), ...rows.map(row => keys.map(key => cell(row[key])).join(','))].join('\n') + '\n' }
async function main(args = process.argv.slice(2), clientFactory = options => new sdk.Client(options)) { try { const options = parse(args); const format = options.format || 'txt'; delete options.format; if (!['txt', 'json', 'csv'].includes(format)) throw new Error('format must be txt, json, or csv'); const source = options.source; delete options.source; const rows = await clientFactory({ source }).getProxies(options); if (!rows.length) return 2; process.stdout.write(format === 'json' ? `${JSON.stringify(rows, null, 2)}\n` : format === 'csv' ? csv(rows) : `${rows.map(sdk.toProxyUrl).join('\n')}\n`); return 0 } catch (error) { process.stderr.write(`${error.message}\n`); return 1 } }
if (require.main === module) main().then(code => { process.exitCode = code })
module.exports = { main }
