import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

const root = resolve(new URL('..', import.meta.url).pathname)
const spec = JSON.parse(await readFile(resolve(root, 'spec/fields.json'), 'utf8'))
const js = `// Generated by scripts/generate-fields.mjs from spec/fields.json. Do not edit.\nexport const CONTRACT_VERSION = ${JSON.stringify(spec.contractVersion)}\nexport const FIELDS = ${JSON.stringify(spec.fields, null, 2)}\n`
const cjs = `'use strict'\n// Generated by scripts/generate-fields.mjs from spec/fields.json. Do not edit.\nmodule.exports = ${JSON.stringify(spec.fields, null, 2)}\n`
const py = `# Generated by scripts/generate-fields.mjs from spec/fields.json. Do not edit.\nCONTRACT_VERSION = ${JSON.stringify(spec.contractVersion)}\nFIELDS = ${JSON.stringify(spec.fields, null, 2).replace(/true/g, 'True').replace(/false/g, 'False').replace(/null/g, 'None')}\n`
const targets = [
  [resolve(root, 'packages/js/src/fields.generated.js'), js],
  [resolve(root, 'packages/js/src/fields.generated.cjs'), cjs],
  [resolve(root, 'packages/python/src/litport_free_proxy_sdk/fields_generated.py'), py],
]
const check = process.argv.includes('--check')
let stale = false
for (const [target, content] of targets) {
  let current = ''
  try { current = await readFile(target, 'utf8') } catch {}
  if (current !== content) {
    stale = true
    if (!check) await writeFile(target, content)
  }
}
if (check && stale) {
  console.error('Generated field tables are stale; run node scripts/generate-fields.mjs')
  process.exitCode = 1
}
