# Generated by scripts/generate-fields.mjs from spec/fields.json. Do not edit.
CONTRACT_VERSION = "1.0.0"
FIELDS = [
  {
    "js": "protocol",
    "python": "protocol",
    "api": "protocol",
    "github": "protocol",
    "Noneable": False
  },
  {
    "js": "ip",
    "python": "ip",
    "api": "host",
    "github": "ip",
    "Noneable": False
  },
  {
    "js": "port",
    "python": "port",
    "api": "port",
    "github": "port",
    "Noneable": False
  },
  {
    "js": "url",
    "python": "url",
    "api": None,
    "github": "url",
    "Noneable": False
  },
  {
    "js": "country",
    "python": "country",
    "api": "geoCountry",
    "github": "country",
    "Noneable": True
  },
  {
    "js": "region",
    "python": "region",
    "api": "geoRegion",
    "github": "region",
    "Noneable": True
  },
  {
    "js": "city",
    "python": "city",
    "api": "geoCity",
    "github": "city",
    "Noneable": True
  },
  {
    "js": "timezone",
    "python": "timezone",
    "api": "geoTimezone",
    "github": "timezone",
    "Noneable": True
  },
  {
    "js": "asn",
    "python": "asn",
    "api": "asn",
    "github": "asn",
    "Noneable": True
  },
  {
    "js": "asnOrg",
    "python": "asn_org",
    "api": "asnOrgName",
    "github": "asn_org",
    "Noneable": True
  },
  {
    "js": "anonymity",
    "python": "anonymity",
    "api": "anonymity",
    "github": "anonymity",
    "Noneable": False
  },
  {
    "js": "https",
    "python": "https",
    "api": "https",
    "github": "https",
    "Noneable": True
  },
  {
    "js": "latencyMs",
    "python": "latency_ms",
    "api": "responseTimeMs",
    "github": "latency_ms",
    "Noneable": True
  },
  {
    "js": "latencyMedianMs",
    "python": "latency_median_ms",
    "api": "responseTimeMedianMs",
    "github": "latency_median_ms",
    "Noneable": True
  },
  {
    "js": "uptime24h",
    "python": "uptime_24h",
    "api": "uptime24h",
    "github": "uptime_24h",
    "Noneable": True
  },
  {
    "js": "uptime7d",
    "python": "uptime_7d",
    "api": "uptime7d",
    "github": "uptime_7d",
    "Noneable": True
  },
  {
    "js": "checks7d",
    "python": "checks_7d",
    "api": "checks7d",
    "github": "checks_7d",
    "Noneable": False
  },
  {
    "js": "exitIp",
    "python": "exit_ip",
    "api": "externalIp",
    "github": "exit_ip",
    "Noneable": True
  },
  {
    "js": "sourcesCount",
    "python": "sources_count",
    "api": "sourcesCount",
    "github": "sources_count",
    "Noneable": False
  },
  {
    "js": "firstSeen",
    "python": "first_seen",
    "api": "createdAt",
    "github": "first_seen",
    "Noneable": False
  },
  {
    "js": "lastChecked",
    "python": "last_checked",
    "api": "pingAt",
    "github": "last_checked",
    "Noneable": False
  }
]
